### ISSUE TITLE
deliveredPackagesCooldown configuration causing problems 

### ISSUE THREAD

**Issue by ChristopherRK** [bureus/MMM-Postnord#2]
```
`WARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: /home/pi/MagicMirror/config/config.js:131
                deliveredPackagesCooldown: "3"
                ^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at loadConfig (/home/pi/MagicMirror/js/app.js:70:12)
    at App.start (/home/pi/MagicMirror/js/app.js:217:3)
    at Object.<anonymous> (/home/pi/MagicMirror/js/electron.js:129:7)
    at Module._compile (internal/modules/cjs/loader.js:786:30)`
```

**Comment by bureus** [comment]
@chris100186 yeah seems like my json in read me is not correct. Will update that during the day, meanwhile here is a working config with correct syntax that you can use:

{
            module: "MMM-Postnord",
            position: "bottom_left",
            config: {
                locale: "sv",
                refreshRateMin: "60",
                deliveredPackagesCooldown: "24"
            }
        },
