### ISSUE TITLE
Included Hash Generator will not run

### ISSUE THREAD

**Issue by oskmy270** [bureus/MMM-Postnord#4]
After `git pull` and `npm install` the guide tells you to run `node postnord-hash-generator.js help`. However, that does not give me the help text needed to go forward, instead it generates an error:
pi@raspberrypi:~/MagicMirror/modules/MMM-Postnord $ node postnord-hash-generator.js help
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'awesome-phonenumber'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Postnord/postnord-hash-generator.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Postnord/postnord-hash-generator.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-Postnord/postnord-hash-generator.js'
  ]
}

**Comment by mickecamino** [comment]
Have you run:
`Run npm install inside ../modules/MMM-Postnord/ folder`
